package consts

const (
	MASTER = "master"

	HTTP_METHOD_GET  string = "GET"
	HTTP_METHOD_POST string = "POST"

	SPOT string = "SPOT"
	SWAP string = "SWAP"

	CROSS    string = "cross"
	ISOLATED string = "isolated"
	MERGE    string = "merge"
	SPLIT    string = "split"

	SIDE_BUY  string = "buy"
	SIDE_SELL string = "sell"

	ORDER_TYPE_MARKET    = "market"
	ORDER_TYPE_LIMIT     = "limit"
	ORDER_TYPE_POST_ONLY = "post_only"
	ORDER_TYPE_IOC       = "ioc"

	POSITION_SIDE_LONG  = "long"
	POSITION_SIDE_SHORT = "short"

	ACCOUNT_BALANCE string = "/deepcoin/v2/account/balances"
	ACCOUNT_UID     string = "/deepcoin/v2/account/uid"
	ACCOUNT_BILLS   string = "/deepcoin/v2/account/bills"
	SET_LEVERAGE    string = "/deepcoin/v2/account/set-leverage"
	POSITIONS       string = "/deepcoin/v2/account/positions"

	MARKET_BOOKS                string = "/deepcoin/v2/market/books"
	MARKET_CANDLES              string = "/deepcoin/v2/market/candles"
	MARKET_INSTRUMENTS          string = "/deepcoin/v2/market/instruments"
	MARKET_TICKERS              string = "/deepcoin/v2/market/tickers"
	MARKET_INDEX_CANDLES        string = "/deepcoin/v2/market/index-candles"
	MARKET_TRADES               string = "/deepcoin/v2/market/trades"
	MARKET_MARK_CANDLES         string = "/deepcoin/v2/market/mark-price-candles"
	MARKET_POSITION_GRADE       string = "/deepcoin/v2/market/step-margin"
	MARKET_BOOK_SPREAD          string = "/deepcoin/v2/market/book-spread"
	MARKET_SYS_TIME             string = "/deepcoin/v2/market/time"
	MARKET_HANDICAP_KLINE1M     string = "/deepcoin/v2/market/handicap-kline1m"
	MARKET_HANDICAP_ORDERBOOK   string = "/deepcoin/v2/market/handicap-orderbook"
	MARKET_HANDICAP_TRADE       string = "/deepcoin/v2/market/handicap-trade"
	MARKET_FUNDING_RATE         string = "/deepcoin/v2/market/funding-rate"
	MARKET_CURRENT_FUNDING_RATE string = "/deepcoin/v2/market/fund-rate/current-funding-rate"
	MARKET_FUNDING_RATE_HISTORY string = "/deepcoin/v2/market/fund-rate/history"
	MARKET_SYS_PING             string = "/deepcoin/v2/market/ping"

	TRADE_ORDER                 string = "/deepcoin/v2/trade/order"
	TRADE_BATCH_ORDERS          string = "/deepcoin/v2/trade/batch-orders"
	TRADE_TRIGGER_ORDER         string = "/deepcoin/v2/trade/trigger-order"
	TRADE_CANCEL_ORDER          string = "/deepcoin/v2/trade/cancel-order"
	TRADE_CANCEL_TRIGGER_ORDER  string = "/deepcoin/v2/trade/cancel-trigger-order"
	TRADE_BATCH_CANCEL_ORDER    string = "/deepcoin/v2/trade/batch-cancel-order"
	TRADE_REPLACE_ORDER         string = "/deepcoin/v2/trade/replace-order"
	TRADE_REPLACE_ORDER_SLTP    string = "/deepcoin/v2/trade/replace-order-sltp"
	TRADE_SET_POSITION_SLTP     string = "/deepcoin/v2/trade/set-position-sltp"
	TRADE_CANCEL_POSITION_SLTP  string = "/deepcoin/v2/trade/cancel-position-sltp"
	TRADE_MODIFY_POSITION_SLTP  string = "/deepcoin/v2/trade/modify-position-sltp"
	TRADE_CANCEL_ORDER_ALL      string = "/deepcoin/v2/trade/swap/cancel-all"
	TRADE_CANCEL_TRIGGER_ALL    string = "/deepcoin/v2/trade/swap/cancel-trigger-all"
	TRADE_BATCH_CLOSE_POSITION  string = "/deepcoin/v2/trade/batch-close-position"
	TRADE_CLOSE_POSITION_BY_IDS string = "/deepcoin/v2/trade/close-position-by-ids"
	TRADE_ORDER_LIST            string = "/deepcoin/v2/trade/order-list"
	TRADE_FILLS                 string = "/deepcoin/v2/trade/fills"
	TRADE_HISTORY_ORDER         string = "/deepcoin/v2/trade/orders-history"
	TRADE_PENDING_ORDER         string = "/deepcoin/v2/trade/orders-pending"
	TRADE_POSITION              string = "/deepcoin/v2/account/positions"
	TRADE_ORDER_BY_ID           string = "/deepcoin/v2/trade/orderByID"
	TRADE_FINISH_ORDER_BY_ID    string = "/deepcoin/v2/trade/finishOrderByID"
	TRADE_FUNDING_RATE          string = "/deepcoin/v2/trade/funding-rate"
	TRADE_BATCH_CANCEL_ORDER_V1 string = "/deepcoin/v2/trade/batch-cancel-order"
	TRADE_PENDING_ORDER_V2      string = "/deepcoin/v2/trade/v2/orders-pending"
	TRADE_SWAP_CANCEL_ALL       string = "/deepcoin/v2/trade/swap/cancel-all"
	TRADE_REPLACE_ORDER_SLTP_V1 string = "/deepcoin/v2/trade/replace-order-sltp"
	TRADE_REPLACE_POS_SLTP      string = "/deepcoin/v2/trade/replace-pos-sltp"

	COPYTRADING_LEADER_SETTINGS  string = "/deepcoin/v2/copytrading/leader-settings"
	COPYTRADING_SUPPORT_CONTRACT string = "/deepcoin/v2/copytrading/support-contracts"
	COPYTRADING_SET_CONTRACT     string = "/deepcoin/v2/copytrading/set-contracts"
	COPYTRADING_LEADER_POSITION  string = "/deepcoin/v2/copytrading/leader-position"
	COPYTRADING_ESTIMATE_PROFIT  string = "/deepcoin/v2/copytrading/estimate-profit"
	COPYTRADING_HISTORY_PROFIT   string = "/deepcoin/v2/copytrading/history-profit"
	COPYTRADING_FOLLOWER_RANK    string = "/deepcoin/v2/copytrading/follower-rank"
	COPYTRADING_GET_ACCOUNTID    string = "/deepcoin/v2/copytrading/get-accountIDs"

	ASSET_DEPOSIT_LIST  = "/deepcoin/v2/asset/deposit-list"
	ASSET_WITHDARW_LIST = "/deepcoin/v2/asset/withdraw-list"

	ListenKey       string = "/deepcoin/v2/listenkey/acquire"
	ExtendListenKey string = "/deepcoin/v2/listenkey/extend"

	INTERNAL_TRANSFER_SUPPORT string = "/deepcoin/v2/internal-transfer/support"
	INTERNAL_TRANSFER         string = "/deepcoin/v2/internal-transfer"
	INTERNAL_TRANSFER_HISTORY string = "/deepcoin/v2/internal-transfer/history-order"
)
